name: Release libs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag name"
        required: true
    
  
jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path src-rust/Cargo.toml

    - name: Release MacOS lib
      if: runner.os == 'MacOS'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/libreedline_rust.dylib
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Linux lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/libreedline_rust.so
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/reedline_rust.dll
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
