name: Release libs

on:
  push:
    tags: 
     - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path reedline-rust/Cargo.toml

    - name: Release MacOS lib
      if: runner.os == 'MacOS'
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/release/libreedline_rust.dylib
        overwrite: true

    - name: Release Linux lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/release/libreedline_rust.so
        overwrite: true

    - name: Release Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/release/reedline_rust.dll
        overwrite: true
