name: Release libs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag name"
        required: true
    
  
jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path src-rust/Cargo.toml

    - name: Release MacOS lib1
      if: runner.os == 'MacOS'
      run: |
        mv src-rust/target/release/libreedline_rust.dylib libreedline_rust_x86_64.dylib

    - name: Release MacOS lib2
      if: runner.os == 'MacOS'
      uses: svenstaro/upload-release-action@v2
      with:
        file: libreedline_rust_x86_64.dylib
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release MacOS arm lib1
      if: runner.os == 'Linux'
      run: |
        rustup target add aarch64-apple-darwin
        cargo build --release --manifest-path src-rust/Cargo.toml --target aarch64-apple-darwin
        mv src-rust/target/aarch64-apple-darwin/release/libreedline_rust.dylib libreedline_rust_aarch64.dylib

    - name: Release MacOS arm lib2
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: libreedline_rust_aarch64.dylib
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Linux lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/libreedline_rust.so
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/reedline_rust.dll
        tag: ${{ github.event.inputs.tag }}
        overwrite: true
